force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Shadow object containing records loaded from an inbound integration with the external PMS. It is a child to Opportunities as the originating source.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceCredentials__c/ServiceCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Username and password credentials for external services</description>
    <label>ServiceCredentials</label>
</CustomObject>

force-app/main/default/objects/ServiceCredentials__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Password for the external service</description>
    <label>Password</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceCredentials__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>User for the external service</description>
    <label>Username</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BillingCalloutService.cls
public class BillingCalloutService {
    
    public static List<Project__c> getProjectDetails(List<Project__c> projectList, Map<Id, Project__c> oldProjectMap) {
        List<Project__c> projects = new List<Project__c>();
        if(projectList != null & !projectList.isEmpty()) {
        	//callBillingService(projectList[0].Id); 
            For(Project__c proj : projectList) {
                if(proj.Status__c == 'Billable' && oldProjectMap.get(proj.Id).Status__c != 'Billable') {
                	projects.add(proj);    
                }
            }   
        } 
        return projects;
    }
    
    @future(callout=true)
    public static void callBillingService(String ProjectId) {
        If(String.isNotBlank(ProjectId)) {
            List<Project__c> projects = [Select Id, Name, Billable_Amount__c, ProjectRef__c, Status__c 
                                         From Project__c
                                         Where Id =: ProjectId]; 
            
            BillingServiceProxy.project billingServiceProject = createProxyProject(projects[0]);
            
            BillingServiceProxy.billProjectRequest_element billProjReqElement = new BillingServiceProxy.billProjectRequest_element();
            billProjReqElement.project = billingServiceProject;
            
            BillingServiceProxy.InvoicesPortSoap11 service = new BillingServiceProxy.InvoicesPortSoap11(); 
            String response = service.billProject(billingServiceProject);
            System.debug('response ====> ' + response);
            if(String.isNotBlank(response) && response == 'OK') {
                Project__c project = new Project__c(Id = ProjectId, Status__c = 'Billed'); 
                Update project;
            }       
        }  
    }
    
    private static BillingServiceProxy.project createProxyProject(Project__c project) {
        BillingServiceProxy.project billingProject = new BillingServiceProxy.project();
        billingProject.username = ServiceCredentials__c.getValues('BillingServiceCredential').Username__c;
        billingProject.password = ServiceCredentials__c.getValues('BillingServiceCredential').Password__c;
        if(project != null) {
            billingProject.projectid = project.ProjectRef__c;
            billingProject.projectRef = project.ProjectRef__c;
            billingProject.billAmount = project.Billable_Amount__c;    
        } 
        return billingProject;
    }
}