force-app/main/default/objects/Bot_Appointment__c/Bot_Appointment__c.object-meta.xml
<CustomObject>
    <description>The Object to be used in Chat Bot for appointment for an agent with customer.</description>
    <label>Bot Appointment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Appointment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bot Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bot_Appointment__c/fields/AppointmentDate__c.field-meta.xml
<CustomField>
    <fullName>AppointmentDate__c</fullName>
    <label>AppointmentDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bot_Appointment__c/fields/AppointmentSlot__c.field-meta.xml
<CustomField>
    <fullName>AppointmentSlot__c</fullName>
    <label>AppointmentSlot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning</fullName>
            </value>
            <value>
                <fullName>Afternoon</fullName>
            </value>
            <value>
                <fullName>Evening</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bot_Appointment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bot Appointments</relationshipLabel>
    <relationshipName>Bot_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bot_Appointment__c/fields/JobType__c.field-meta.xml
<CustomField>
    <fullName>JobType__c</fullName>
    <label>JobType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>BreakAndFix</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bot_Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Bot_GetOpenAppointments.cls
public With Sharing class Bot_GetOpenAppointments {

    @InvocableMethod(label='Get Open Appointments')
    public static List<List<Bot_Appointment__c>> getOpenAppointments(List<String> emailList) {
        String sEmail = emailList[0];
        
        // Create a list for the appointments
        // NOTE: This is a list of lists in order to handle bulk calls...
        List<List<Bot_Appointment__c>> appointmentList = new List<List<Bot_Appointment__c>>();

        // Get the list of new and scheduled appointments
		List<Bot_Appointment__c> appointments = [SELECT Id, Name, JobType__c, AppointmentDate__c, AppointmentSlot__c 
                                             	 FROM Bot_Appointment__c 
                                                 WHERE Contact__r.Email =:sEmail 
                                                 AND Status__c IN ('New','Scheduled')];
        
        // Add all the new and scheduled appointments to the list
        if(appointments != null && appointments.size() > 0) {
        	appointmentList.add(appointments);    
        }
        return appointmentList;
    }
}