force-app/main/default/objects/Camping_Item__c/Camping_Item__c.object-meta.xml
<CustomObject>
    <label>Camping Item</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Camping Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Camping Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camping_Item__c/fields/Packed__c.field-meta.xml
<CustomField>
    <fullName>Packed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Packed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CampingListController.cls
public with sharing class CampingListController {
	@AuraEnabled
    public static List<Camping_Item__c> getItems() {
    	List<Camping_Item__c> campingItemList = [Select Id, Name, Packed__c, Price__c, Quantity__c
                                                 From Camping_Item__c];
        return campingItemList;
    }
    @AuraEnabled
    public static Camping_Item__c saveItem(Camping_Item__c campingItem) {
        if(campingItem != null) {
            Upsert campingItem;
        }
        return campingItem;
    }
}